apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gago
  title: Gagoo
  description: Product Owner of Splitz.
spec:
  profile:
    displayName: Gagoooo
    email: gagog.doe@example.com
  memberOf:
    - splitz-team