apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: edward
  title: Edward
  description: UI Lead for the Splitz Team.
spec:
  profile:
    displayName: Edward
    email: Edward.smith@example.com
  # 🔗 TEAM: Links the user back to their group.
  memberOf:
    - splitz-team