catalog:
  # Base URL for the Catalog backend
  baseUrl: http://localhost:7007/catalog
  
  # 🎯 The Locations section tells Backstage where to find your YAML files
  locations:
    # 💡 Solution for Ingesting Multiple Split Files (Groups, Users, Systems, APIs, Components)
    - type: url
      # ⚠️ IMPORTANT: Set the 'target' to the base directory containing all your split folders.
      # This example assumes all your entity files are within a 'catalog/' folder
      # in the 'main' branch of the 'pvo15/bulkiii' repository.
      target: https://github.com/pvo15/bulkiii/blob/main/catalog/
      
      # ➡️ The 'rules' section uses a GLOB pattern (**) to find any .yaml or .yml file
      # inside any subdirectory of the 'catalog/' folder.
      rules:
        # This single rule discovers files like:
        # - catalog/groups/group-splitz-team.yaml
        # - catalog/users/user-gago.yaml
        # - catalog/components/component-bulk-worker-service.yaml
        - allow: [ Group, User, Component, System, API ] # Must allow all entity kinds
          pattern: '**/(*.yaml|*.yml)'
