# app-config.yaml (Backstage Backend Configuration)

catalog:
  locations:
    # Remote catalog (GitHub raw URL)
    - type: url
      target: https://raw.githubusercontent.com/pvo15/bulkiii/main/catalog-info.yaml
      rules:
        - allow: [ Group, User, Component, API, System ]

    # Or, if you keep it local to the repo:
    # - type: file
    #   target: ./catalog-info.yaml
    #   rules:
    #     - allow: [ Group, User, Component, API, System ]

  processors:
    github:
      providerId: 'github-production'
      catalog:
        allow: [ Group, User, Component, API, System ]
