# app-config.yaml (Backstage Backend Configuration)
apiVersion: backstage.io/v1alpha1
catalog:
  locations:
    # Assuming this is the location you registered for the consolidated file
    - type: url
      target: ./catalog-info.yaml
      # 🚨 THE FIX: Add explicit rules to allow ALL entity kinds present in the file
      rules:
        - allow: [ Group, User, Component, API ] # <--- Ensure all Kinds are listed here
    
    # ... any other existing locations ...

  # If you are using an integration to discover entities from an organization
  processors:
    github:
      # If this processor is also scanning the repo, ensure its settings 
      # allow all the required entity kinds. 
      # Check your full processor configuration if the error persists.
      # For example:
      providerId: 'github-production'
      catalog:
        allow: [ Group, User, Component, API ] # <--- Ensure this is broad enough
