apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-splitz
  description: Splitz
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: splitz.com
    picture: https://sprintonline.am/squidex-client/api/assets/client/59521d2a-0239-4ef9-ba94-1a5d4c319513
  parent: backstage
  children: []
  
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: Gago.davison
spec:
  profile:
    # Intentional no displayName for testing
    email: gago-davison@example.com
    picture: https://sprintonline.am/squidex-client/api/assets/client/59521d2a-0239-4ef9-ba94-1a5d4c319513
  memberOf: [team-Splitz]



apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulkiii
  annotations:
    github.com/project-slug: pvo15/bulkiii
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
spec:
  type: service
  lifecycle: experimental
  owner: team-splitz
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
  apiConsumedBy: ['component:www-artist']
  targets:
    - ./apis/hello-world-api.yaml
    - ./apis/hello-world-trpc-api.yaml
    - ./apis/petstore-api.yaml
    - ./apis/petstore-webhook-api.yaml
    - ./apis/spotify-api.yaml
    - ./apis/streetlights-api.yaml
    - ./apis/swapi-graphql.yaml
    - ./apis/wayback-archive-api.yaml
    - ./apis/wayback-search-api.yaml
