apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: bulkiii-catalog
  description: Central location for managing the Bulkiii project catalog entities.
spec:
  type: url
  targets:
    - ./catalog/groups/group-splitz-team.yaml
    - ./catalog/users/user-gago.yaml
    - ./catalog/users/user-edward.yaml
#    - ./catalog/systems/system-splitz.yaml
#    - ./catalog/components/component-bulk-worker-service.yaml
    - ./catalog/apis/api-bulk-ingestion.yaml