apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Splitz-dashboard
  title: Splitz Dashboard
  description: User interface for tracking and managing Splitz processing jobs.
  tags:
    - react
    - ui
    - core
  annotations:
    github.com/project-slug: pvo15/bulkiii
spec:
  type: website
  lifecycle: production
  owner: group:splitz-team
  system: bulk-processing-system
  consumesApis:
    - bulk-ingestion-api
