# Catalog Info for Splitz Online Lending System
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: splitz-lending-system
  description: Central hub for managing Splitz project components in Backstage Catalog.
spec:
  type: url
  targets:
    - ./catalog/systems/system-splitz.yaml
    - ./catalog/groups/group-splitz-team.yaml
    - ./catalog/users/user-gago.yaml
    - ./catalog/components/component-bulk-status-dashboard.yaml
    - ./catalog/components/component-bulk-validator-lib.yaml
    - ./catalog/components/component-bulk-worker-service.yaml