# catalog-info.yaml - Consolidated Entity Definitions

# ----------------------------------------------------------------------
# 1. TEAM (Kind: Group)
# Defines the team that owns all related entities.
# ----------------------------------------------------------------------
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: splitz-team
  title: Sprint online Team
  description: Get a loan with us.
spec:
  type: team
  profile:
    displayName: Splitz Team
    email: splitz-team@example.com
  parent: engineering-department 
  children: []
  # 🔗 MEMBERS: Lists the User entities belonging to this team.
  members:
    - user:gago
    - user:edward

---
# ----------------------------------------------------------------------
# 2. MEMBERS (Kind: User)
# Defines two user entities that are members of the team.
# ----------------------------------------------------------------------
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gago
  title: Gagoo
  description: Product Owner of Splitz.
spec:
  profile:
    displayName: Gagoooo
    email: gagog.doe@example.com
  # 🔗 TEAM: Links the user back to their group.
  memberOf:
    - splitz-team

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: edward
  title: Edward
  description: UI Lead for the Splitz  Team.
spec:
  profile:
    displayName: Edward
    email: Edward.smith@example.com
  # 🔗 TEAM: Links the user back to their group.
  memberOf:
    - splitz-team

---
# ----------------------------------------------------------------------
# 3. API (Kind: API)
# Defines the API used by the service and the UI component.
# ----------------------------------------------------------------------
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bulk-ingestion-api
  title: Bulk Ingestion REST API
  description: Handles initial data submission and status checks for bulk jobs.
  tags:
    - rest
    - production
spec:
  type: openapi
  lifecycle: production
  # 🔗 TEAM: The API is owned by the Bulk Core Team.
  owner: group:splitz-team
  system: bulk-processing-system
  definition:
    $text: https://github.com/example-org/bulk-ingestion-api/blob/main/openapi.yaml

---
# ----------------------------------------------------------------------
# 4. SERVICES (Kind: Component, Type: service)
# Defines the backend worker service.
# ----------------------------------------------------------------------
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-worker-service
  title: Bulk Worker Service
  description: Asynchronous service to process bulk jobs.
  tags:
    - java
    - queue
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/example-org/bulk-worker-service/blob/main/docs
spec:
  type: service
  lifecycle: production
  # 🔗 TEAM: Owned by the Bulk Core Team.
  owner: group:splitz-team
  system: bulk-processing-system
  # 🔗 API: Consumes its own defined API (or provides a messaging API).
  consumesApis:
    - bulk-ingestion-api

---
# ----------------------------------------------------------------------
# 5. LIBS (Kind: Component, Type: library)
# Defines a reusable library used by the service and UI.
# ----------------------------------------------------------------------
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-validator-lib
  title: Bulk Data Validator Library
  description: Common logic for validating incoming data formats.
  tags:
    - shared
    - python
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/example-org/bulk-validator-lib/blob/main/docs
spec:
  type: library
  lifecycle: production
  # 🔗 TEAM: Owned by the Bulk Core Team.
  owner: group:splitz-team
  system: bulk-processing-system

---
# ----------------------------------------------------------------------
# 6. UI COMPONENTS (Kind: Component, Type: website)
# Defines the frontend UI component, linked to the user's provided repository.
# ----------------------------------------------------------------------
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-status-dashboard
  title: Bulk Status Dashboard
  description: User interface for tracking and managing bulk processing jobs.
  tags:
    - react
    - ui
  annotations:
    # 🔗 CODE: Links to the GitHub repository provided by the user.
    github.com/project-slug: pvo15/bulkiii
spec:
  type: website
  lifecycle: production
  # 🔗 TEAM: Owned by the Bulk Core Team.
  owner: group:splitz-team
  system: bulk-processing-system
  # 🔗 API: Consumes the Bulk Ingestion API to display job status.
  consumesApis:
    - bulk-ingestion-api
