apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: bulkiii-groups
  description: Location for Groups
spec:
  targets:
    - ./catalog/groups/all-groups.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: bulkiii-users
  description: Location for Users
spec:
  targets:
    - ./catalog/groups/all-users.yaml