apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering-department
  title: Engineering Department
  description: Parent group for engineering teams.
spec:
  type: department
  profile:
    displayName: Engineering Department
    email: engineering@example.com
  children:
    - splitz-team
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: splitz-team
  title: Sprint Online Team
  description: Get a loan with us.
spec:
  type: team
  profile:
    displayName: Splitz Team
    email: splitz-team@example.com
  parent: engineering-department
  children: []
  members:
    - user:gago
    - user:edward
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gago
  title: Product Owner
  description: Product Owner of Splitz.
spec:
  profile:
    displayName: Gagoooo
    email: gagog.doe@example.com
  memberOf:
    - splitz-team
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: edward
  title: UI Lead
  description: UI Lead for the Splitz Team.
spec:
  profile:
    displayName: Edward
    email: edward.smith@example.com
  memberOf:
    - splitz-team
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bulk-ingestion-api
  title: Bulk Ingestion REST API
  description: Handles initial data submission and status checks for bulk jobs.
  tags:
    - rest
    - production
spec:
  type: openapi
  lifecycle: production
  owner: group:splitz-team
  system: bulk-processing-system
  definition:
    $text: https://github.com/example-org/bulk-ingestion-api/blob/main/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-worker-service
  title: Bulk Worker Service
  description: Asynchronous service to process bulk jobs.
  tags:
    - java
    - queue
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/example-org/bulk-worker-service/blob/main/docs
spec:
  type: service
  lifecycle: production
  owner: group:splitz-team
  system: bulk-processing-system
  consumesApis:
    - bulk-ingestion-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-validator-lib
  title: Bulk Data Validator Library
  description: Common logic for validating incoming data formats.
  tags:
    - shared
    - python
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/example-org/bulk-validator-lib/blob/main/docs
spec:
  type: library
  lifecycle: production
  owner: group:splitz-team
  system: bulk-processing-system
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-status-dashboard
  title: Bulk Status Dashboard
  description: User interface for tracking and managing bulk processing jobs.
  tags:
    - react
    - ui
  annotations:
    github.com/project-slug: pvo15/bulkiii
spec:
  type: website
  lifecycle: production
  owner: group:splitz-team
  system: bulk-processing-system
  consumesApis:
    - bulk-ingestion-api
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bulk-processing-system
  title: Bulk Processing System
  description: System responsible for ingestion, validation, and processing of bulk jobs.
spec:
  owner: group:splitz-team
