apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-status-dashboard
  title: Bulk Status Dashboard
  description: User interface for tracking and managing bulk processing jobs.
  tags:
    - react
    - ui
  annotations:
    github.com/project-slug: pvo15/bulkiii
spec:
  type: website
  lifecycle: production
  owner: group:splitz-team
  system: bulk-processing-system
  consumesApis:
    - bulk-ingestion-api
