apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: bulk-catalog
spec:
  targets:
    - ./catalog/components/backend.yaml
    - ./catalog/components/splitz-web.yaml
    - ./catalog/components/quantum-lib.yaml