apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: Splytz-catalog
spec:
  targets:
    - ./catalog/systems/fraud-guard.yaml
    - ./catalog/apis/ingestion-api.yaml
    - ./catalog/components/getaway.yaml
    - ./catalog/components/backend.yaml
    - ./catalog/components/material-ui.yaml
    - ./catalog/components/splitz-web.yaml
    - ./catalog/components/quantum-lib.yaml