apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: splitz-catalog
  description: Central hub for managing Splitz project entities in the Backstage Catalog.
spec:
  type: file
  targets:
    - ./catalog/groups/group-splitz-team.yaml
