apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: Splytz-catalog
spec:
  targets:
    - ./catalog/systems/fraud-guard.yaml
    - ./catalog/resources/db-resources.yaml
    - ./catalog/resources/redis.yaml
    - ./catalog/resources/awstorage.yaml
    - ./catalog/apis/ingestion-api.yaml
    - ./catalog/apis/mfa-api.yaml
    - ./catalog/components/mfa-module.yaml
    - ./catalog/components/splytzmodule.yaml
    - ./catalog/components/fraudguard.yaml
    - ./catalog/components/accesscontrol.yaml
    - ./catalog/components/getaway.yaml
    - ./catalog/components/backend.yaml
    - ./catalog/components/material-ui.yaml
    - ./catalog/components/splitz-web.yaml
    - ./catalog/components/quantum-lib.yaml