# catalog/groups/group-splitz-team.yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: splitz-team
  title: Sprint online Team
  description: Team responsible for the "splitz" online lending system.
spec:
  type: team
  profile:
    displayName: Splitz Team
    email: splitz-team@example.com
  parent: engineering-department
  children: []
  # 🔗 MEMBERS: Lists the User entities belonging to this team.
  members:
    - bulki:gest
