apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bulk-ingestion-api
  title: Bulk Ingestion REST API
  description: Handles initial data submission and status checks for bulk jobs.
spec:
  type: openapi
  lifecycle: production
  owner: team-c
  definition: |
    import { z } from 'zod';
    import { publicProcedure, router } from '../trpc';
    
    export const apiRouter = router({
      version: publicProcedure.query(() => {
        return { version: '0.42.0' };
      }),
      hello: publicProcedure
        .input(z.object({ username: z.string().nullish() }).nullish())
        .query(({ input, ctx }) => {
          return {
            text: `hello ${input?.username ?? ctx.user?.name ?? 'world'}`,
          };
        }),
    });