apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bulk-ingestion-api
  title: Bulk Ingestion REST API
  description: Handles initial data submission and status checks for bulk jobs.
spec:
  type: openapi
  lifecycle: production
  owner: splitz-team
  definition:
    $text: https://github.com/example-org/bulk-ingestion-api/blob/main/openapi.yaml