apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: splitz-team
  title: Splitz Team
  description: Team responsible for Splitz online lending system.
spec:
  type: team
  profile:
    displayName: Splitz Team
    email: splitz-team@example.com
  parent: engineering-department
  children: []
  members:
    - user:edward
