# catalog/components/accesscontrol.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: accesscontrol
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/example-org/bulk-worker-service/blob/main/docs
spec:
  type: service
  lifecycle: production
  owner: group:splitz-team
  dependsOn:
    -component:bootstrapper
    -resource:redis
