# catalog/components/backend.yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: back-end-service
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/example-org/bulk-worker-service/blob/main/docs
spec:
  type: service
  lifecycle: production
  owner: group:splitz-team
  # 🔗 API: Consumes its own defined API.
  providesApis:
    - ingestion-api
  dependsOn:
    - component:getaway