# catalog/components/getaway.yaml
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  name: getaway
  title: Getaway Service
spec:
  type: service
  lifecycle: production
  owner: group:splitz-team
